services:
  # Development Portfolio Next.js Application
  app:
    build:
      context: ../../services/nextjs
      dockerfile: ../../deploy/docker/Dockerfile.dev
    container_name: portfolio-app-dev
    restart: unless-stopped
    labels:
      kompose.namespace: portfolio
    ports:
      - 3005:3000
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - portfolio-network
    volumes:
      - ../../services/nextjs:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  portfolio-network:
    driver: bridge
    name: portfolio-network-dev
