apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/portfolio
    newTag: main-sha-db21ed85671bdb8b6153d06250e41821772003dc

patchesStrategicMerge:
  - deployment-patch.yaml
