apiVersion: v1
kind: ResourceQuota
metadata:
  name: portfolio-quota
  namespace: portfolio
spec:
  hard:
    requests.memory: "250Mi"
    requests.cpu: "200m"
    limits.memory: "400Mi"
    limits.cpu: "400m"
    pods: "3"
